ALTER TYPE "ErrAction" ADD VALUE IF NOT EXISTS 'FINALIZED_APPROVAL';
ALTER TYPE "ErrAction" ADD VALUE IF NOT EXISTS 'ESCALATED_TO_ACTING_CEO';
ALTER TYPE "ErrAction" ADD VALUE IF NOT EXISTS 'ESCALATED_TO_CEO';